# Generated by ChatGPT on 2026-02-09

from __future__ import annotations

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("refunds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundAttempt",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("status", models.CharField(max_length=16, choices=[("success", "Success"), ("error", "Error")])),
                ("stripe_refund_id", models.CharField(blank=True, default="", max_length=255)),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="refund_attempts", to=settings.AUTH_USER_MODEL)),
                ("refund_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="refunds.refundrequest")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="refunds_ref_status_8b55a9_idx"),
                    models.Index(fields=["refund_request", "-created_at"], name="refunds_ref_refund__c4fa19_idx"),
                ],
            },
        ),
    ]
