# Generated by Home Craft 3D (local DB reset hardening)

from __future__ import annotations

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refunds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=64, blank=True, default="")),
                ("success", models.BooleanField(default=False)),
                (
                    "stripe_refund_id",
                    models.CharField(max_length=255, blank=True, default=""),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="refunds.refundrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["refund_request", "-created_at"],
                        name="refunds_ref_refund__a1d0a3_idx",
                    ),
                    models.Index(
                        fields=["success", "-created_at"],
                        name="refunds_ref_success_7f2c1a_idx",
                    ),
                ],
            },
        ),
    ]
