# Generated by Django 5.1.15 on 2026-02-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_refundattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refundattempt',
            new_name='refunds_ref_status_a3a8f1_idx',
            old_name='refunds_ref_status_8b55a9_idx',
        ),
        migrations.RenameIndex(
            model_name='refundattempt',
            new_name='refunds_ref_refund__b8d9f8_idx',
            old_name='refunds_ref_refund__c4fa19_idx',
        ),
    ]
