# Generated by Django 5.1.15 on 2026-02-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0003_rename_refunds_ref_status_8b55a9_idx_refunds_ref_status_a3a8f1_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefundAttempt',
        ),
    ]
