# Generated by ChatGPT on 2026-02-09
from django.db import migrations, models
from django.conf import settings
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("refunds", "0004_delete_refundattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundAttempt",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("request_id", models.CharField(max_length=64, blank=True, default="")),
                ("success", models.BooleanField(default=False)),
                ("stripe_refund_id", models.CharField(max_length=255, blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="refund_attempts", to=settings.AUTH_USER_MODEL)),
                ("refund_request", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="attempts", to="refunds.refundrequest")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["success", "-created_at"], name="refunds_ref_success_5b8f77_idx"),
                    models.Index(fields=["-created_at"], name="refunds_ref_created_7e4e3d_idx"),
                ],
            },
        ),
    ]
