# Generated by Django 5.1.15 on 2026-02-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0005_refundattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refundattempt',
            new_name='refunds_ref_success_98ce8f_idx',
            old_name='refunds_ref_success_5b8f77_idx',
        ),
        migrations.RenameIndex(
            model_name='refundattempt',
            new_name='refunds_ref_created_42bbfb_idx',
            old_name='refunds_ref_created_7e4e3d_idx',
        ),
    ]
