# Generated by Django 5.1.15 on 2026-02-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_seed_licensing_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='body',
            field=models.TextField(help_text='HTML is allowed. Content is rendered as trusted HTML (admin-only editing).'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='doc_type',
            field=models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('refund', 'Refund Policy'), ('content', 'Content & Safety Policy'), ('digital_license', 'Digital Product License'), ('seller_agreement', 'Seller Agreement'), ('physical_policy', 'Physical Product Policy')], max_length=24),
        ),
    ]
