# Generated by Django 5.1.15 on 2026-02-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphysical',
            name='num_colors',
            field=models.PositiveIntegerField(blank=True, help_text='Number of colors in this print', null=True),
        ),
        migrations.AddField(
            model_name='productphysical',
            name='specifications',
            field=models.TextField(blank=True, help_text='Additional specifications (e.g., scale info, assembly instructions, etc.)'),
        ),
        migrations.AddField(
            model_name='productphysical',
            name='support_required',
            field=models.BooleanField(default=False, help_text='Does this model require supports for printing?'),
        ),
        migrations.AddField(
            model_name='productphysical',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in grams', null=True),
        ),
    ]
