# Generated by Django 5.1.15 on 2026-02-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_digitalasset_download_count_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphysical',
            name='depth_mm',
        ),
        migrations.RemoveField(
            model_name='productphysical',
            name='height_mm',
        ),
        migrations.RemoveField(
            model_name='productphysical',
            name='width_mm',
        ),
        migrations.AddField(
            model_name='productphysical',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productphysical',
            name='dimension_unit',
            field=models.CharField(choices=[('mm', 'Millimeters (mm)'), ('in', 'Inches (in)')], default='mm', max_length=2),
        ),
        migrations.AddField(
            model_name='productphysical',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productphysical',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='productphysical',
            name='weight_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams', max_digits=8, null=True),
        ),
    ]
