# Generated by Django 5.1.15 on 2026-02-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text='Optional Facebook page URL for footer icon.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text='Optional Instagram profile URL for footer icon.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', help_text='Optional LinkedIn page URL for footer icon.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tiktok_url',
            field=models.URLField(blank=True, default='', help_text='Optional TikTok profile URL for footer icon.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='x_url',
            field=models.URLField(blank=True, default='', help_text='Optional X (Twitter) profile URL for footer icon.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='youtube_url',
            field=models.URLField(blank=True, default='', help_text='Optional YouTube channel URL for footer icon.'),
        ),
    ]
