# Generated by Django 5.1.15 on 2026-02-06 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_advertisementbanner_siteemailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteemailtemplate',
            name='site_config',
            field=models.ForeignKey(blank=True, help_text='Site config this template belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='core.siteconfig'),
        ),
    ]
