# Generated by Django 5.1.15 on 2026-02-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_siteconfig_home_banner_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='home_banner_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, show a banner on the home page (only).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_banner_text',
            field=models.CharField(blank=True, default='', help_text='Text shown in the home page banner. Keep it short.', max_length=240),
        ),
    ]
