# Generated by Django 5.1.15 on 2026-02-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_siteconfig_affiliate_disclosure_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='free_digital_listing_cap',
            field=models.PositiveIntegerField(default=5, help_text='Max number of ACTIVE free digital FILE listings a seller may have without completing Stripe onboarding.'),
        ),
    ]
