# Generated by Django 5.1.15 on 2026-02-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_alter_legaldocument_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='doc_type',
            field=models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('refund', 'Refund Policy'), ('content', 'Content & Safety Policy'), ('digital_license', 'Digital Product License'), ('seller_agreement', 'Seller Agreement'), ('physical_policy', 'Physical Product Policy'), ('seller_fees', 'Seller Fees')], max_length=24),
        ),
    ]
