# Generated by Django 5.1.15 on 2026-02-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_merge_20260211_0836'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_visitor_cc66fd_idx',
            old_name='analytics_v_vid_created_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_session_533ea7_idx',
            old_name='analytics_v_sid_created_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_host_58ad35_idx',
            old_name='analytics_v_host_created_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_environ_4119fc_idx',
            old_name='analytics_v_env_created_idx',
        ),
    ]
