# Generated by Django 5.1.15 on 2026-02-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siteconfig_home_banner_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='home_banner_enabled',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='home_banner_text',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='promo_banner_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, show a promo banner above the navbar sitewide.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='promo_banner_text',
            field=models.CharField(blank=True, default='', help_text='Text shown in the promo banner. Keep it short.', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='seller_fee_waiver_days',
            field=models.PositiveIntegerField(default=30, help_text='Length of new-seller fee waiver window in days.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='seller_fee_waiver_enabled',
            field=models.BooleanField(default=True, help_text='If enabled, new sellers receive a temporary 0% marketplace cut.'),
        ),
    ]
