# Generated by ChatGPT on 2026-02-09
from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0001_initial"),
        ("core", "0010_remove_siteconfig_home_banner_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("qa_report_resolved", "Q&A report resolved"), ("qa_message_removed", "Q&A message removed"), ("user_suspended", "User suspended")], db_index=True, max_length=40)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(blank=True, help_text="Staff user who performed the action.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff_actions", to=settings.AUTH_USER_MODEL)),
                ("qa_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff_actions", to="qa.productquestionmessage")),
                ("qa_report", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff_actions", to="qa.productquestionreport")),
                ("target_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff_actions_targeted", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="staffactionlog",
            index=models.Index(fields=["action", "-created_at"], name="core_staff_action_idx"),
        ),
        migrations.AddIndex(
            model_name="staffactionlog",
            index=models.Index(fields=["-created_at"], name="core_staff_created_idx"),
        ),
    ]
