# Generated by Django 5.1.15 on 2026-02-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteconfig_home_banner_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='affiliate_disclosure_text',
            field=models.CharField(blank=True, default='As an Amazon Associate I earn from qualifying purchases.', help_text='Short disclosure shown under the affiliate links (recommended).', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='affiliate_links',
            field=models.JSONField(blank=True, default=list, help_text="List of links shown in the sidebar. Example item: {'label':'SUNLU PLA 1kg','url':'https://...','note':'Budget PLA+'} (label+url required; note optional)."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='affiliate_links_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, show affiliate product links (e.g., Amazon Associates) in the store sidebar.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='affiliate_links_title',
            field=models.CharField(blank=True, default='Recommended Filament & Gear', help_text='Sidebar section heading for affiliate links.', max_length=80),
        ),
    ]
