# Generated by ChatGPT on 2026-02-10
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_core_staff_action_idx_core_staffa_action_7ad111_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="google_analytics_dashboard_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Google Analytics dashboard URL (for quick access from the admin dashboard).",
            ),
        ),
    ]
