# Generated by Django 5.1.15 on 2026-02-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short public bio/about for your shop.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='Facebook profile URL.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_twitter',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_youtube',
            field=models.URLField(blank=True, help_text='YouTube channel URL.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, help_text='Personal or shop website.'),
        ),
    ]
