# Generated by Django 5.1.15 on 2026-02-02 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_stripewebhookevent_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBalanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.IntegerField(help_text='Signed cents. Positive = owed to seller, negative = seller owes platform.')),
                ('reason', models.CharField(choices=[('payout', 'Payout'), ('refund', 'Refund'), ('chargeback', 'Chargeback'), ('adjustment', 'Manual adjustment')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_balance_entries', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_balance_entries', to='orders.orderitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['seller', '-created_at'], name='payments_se_seller__2b9460_idx'), models.Index(fields=['reason', '-created_at'], name='payments_se_reason_8966a2_idx')],
            },
        ),
    ]
