# Generated by Django 5.1.15 on 2026-02-06 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_carrier'),
        ('payments', '0003_alter_sellerbalanceentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerbalanceentry',
            name='reason',
            field=models.CharField(choices=[('sale', 'Sale (order paid)'), ('payout', 'Payout'), ('refund', 'Refund'), ('chargeback', 'Chargeback'), ('adjustment', 'Manual adjustment')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='sellerbalanceentry',
            constraint=models.UniqueConstraint(fields=('seller', 'order', 'reason'), name='uniq_seller_order_reason'),
        ),
    ]
