# Generated by Django 5.1.15 on 2026-02-01 21:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_sales_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percent of sales withheld by the marketplace (e.g., 10.00 = 10%).', max_digits=6)),
                ('platform_fee_cents', models.PositiveIntegerField(default=0, help_text='Optional fixed fee in cents added to each order (0 disables).')),
                ('default_currency', models.CharField(default='usd', help_text="Default currency (Stripe-style), e.g. 'usd'.", max_length=8)),
                ('allowed_shipping_countries', models.JSONField(blank=True, default=list, help_text="List of allowed country codes for shipping (e.g. ['US']).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Config',
            },
        ),
    ]
