# Generated by Django 5.1.15 on 2026-02-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteemailtemplate_site_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='home_banner_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, show a promotional banner above the navbar on the home page.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_banner_text',
            field=models.CharField(blank=True, default='', help_text='Banner text displayed above the navbar on the home page.', max_length=280),
        ),
    ]
