# Generated by Django 5.1.15 on 2026-02-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20260209_1734'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffactionlog',
            new_name='core_staffa_action_7ad111_idx',
            old_name='core_staff_action_idx',
        ),
        migrations.RenameIndex(
            model_name='staffactionlog',
            new_name='core_staffa_created_11c74b_idx',
            old_name='core_staff_created_idx',
        ),
        migrations.AlterField(
            model_name='staffactionlog',
            name='action',
            field=models.CharField(choices=[('qa_report_resolved', 'Q&A report resolved'), ('qa_message_removed', 'Q&A message removed'), ('user_suspended', 'User suspended'), ('user_unsuspended', 'User unsuspended')], db_index=True, max_length=40),
        ),
    ]
