# Generated by Django 5.1.15 on 2026-02-03 16:22

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_sellerbalanceentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerbalanceentry',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='sellerbalanceentry',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='sellerstripeaccount',
            index=models.Index(fields=['stripe_account_id'], name='payments_se_stripe__722205_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerstripeaccount',
            index=models.Index(fields=['details_submitted', 'charges_enabled', 'payouts_enabled'], name='payments_se_details_2e0821_idx'),
        ),
    ]
