# Generated by Django 5.1.15 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_digitalasset_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalasset",
            name="zip_contents",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
