# Generated by Django 5.1.15 on 2026-02-04 20:11

import core.storage_backends
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_digitalasset_zip_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalasset',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('C:/Users/mprov/Dropbox/Projects/home_craft_3d/home_craft_3d/media')), upload_to='digital_assets/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=core.storage_backends.get_media_storage, upload_to='product_images/'),
        ),
    ]
