# Generated by Django 5.1.15 on 2026-02-04 21:25

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_digitalasset_file_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalasset',
            name='file',
            field=models.FileField(storage=core.storage_backends.DownloadsStorage(), upload_to='digital_assets/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
