# Generated by Django 5.1.15 on 2026-02-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_digitalasset_file_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complexity_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Difficulty level for this 3D file/model', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='print_time_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated print time in hours', null=True),
        ),
    ]
