# Generated by Django 5.1.15 on 2026-02-07 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_rootcategory_rootcategory'),
        ('products', '0010_product_max_purchases_per_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Subcategory under the main category.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_subcategory', to='catalog.category'),
        ),
    ]
