# Generated by Django 5.1.15 on 2026-02-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_slug_is_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilamentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('pla', 'PLA / PLA+'), ('petg', 'PETG'), ('abs', 'ABS'), ('asa', 'ASA'), ('tpu', 'TPU'), ('nylon', 'Nylon')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('url', models.URLField(help_text='External or affiliate link')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filament_recommendations', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'material', 'id'],
                'indexes': [models.Index(fields=['product', 'is_active', 'sort_order'], name='products_fi_product_6a1526_idx'), models.Index(fields=['material', 'is_active'], name='products_fi_materia_d7162d_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'material', 'url'), name='uniq_filament_reco_product_material_url')],
            },
        ),
    ]
