# Generated by Django 5.1.15 on 2026-02-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_theme_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='theme_accent',
            field=models.CharField(default='#F97316', help_text='Accent color (hex).', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='theme_dark_bg',
            field=models.CharField(default='#0B1220', help_text='Dark mode background (hex).', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='theme_default_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Default mode for new visitors (users may toggle).', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='theme_light_bg',
            field=models.CharField(default='#F9FAFB', help_text='Light mode background (hex).', max_length=20),
        ),
    ]
