# Generated by Django 5.1.15 on 2026-02-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_staffactionlog'),
        ('core', '0013_siteconfig_free_digital_listing_cap'),
    ]

    operations = [
    ]
