# Generated by Django 5.1.15 on 2026-02-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_buyer_notified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buyer_notes',
            field=models.TextField(blank=True, default='', help_text='Special instructions or notes from the buyer for this item.'),
        ),
    ]
