# Generated by ChatGPT on 2026-02-09

from __future__ import annotations

import uuid

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_orderitem_is_tip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookDelivery",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("received", "Received"), ("processed", "Processed"), ("error", "Error")], default="received", max_length=32)),
                ("request_id", models.CharField(blank=True, default="", help_text="X-Request-ID if present.", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "-received_at"], name="orders_stri_status_1d2b32_idx"),
                    models.Index(fields=["event_type", "-received_at"], name="orders_stri_event_t_b0b5fa_idx"),
                ],
            },
        ),
    ]
