# Generated by Django 5.1.15 on 2026-02-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfig_home_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='plausible_shared_url',
            field=models.URLField(blank=True, default='', help_text='Plausible shared dashboard URL (read-only). Example: https://plausible.io/share/<site>?auth=...'),
        ),
    ]
