# Generated by Django 5.1.15 on 2026-02-06 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfig_plausible_shared_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ad_banners/')),
                ('link_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template identifier (e.g. 'staff_announcement')", max_length=100, unique=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('body', models.TextField(help_text='Email body. You can use {{ user }}, {{ site_name }}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Email Template',
                'verbose_name_plural': 'Site Email Templates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
