# Generated by Django 5.1.15 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalasset",
            name="file_type",
            field=models.CharField(
                blank=True,
                null=True,
                choices=[
                    ("stl", ".stl"),
                    ("3mf", ".3mf"),
                    ("obj", ".obj"),
                    ("zip", ".zip"),
                ],
                max_length=10,
            ),
        ),
    ]
