# Generated by Django 5.1.15 on 2026-02-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_filamentrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalasset',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
    ]
