# Generated by Django 5.1.15 on 2026-02-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productdownloadevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productdownloadevent',
            new_name='products_pr_product_6eab5e_idx',
            old_name='products_pr_product__9b3f4b_idx',
        ),
        migrations.RenameIndex(
            model_name='productdownloadevent',
            new_name='products_pr_product_37e3b3_idx',
            old_name='products_pr_product__a8c9c6_idx',
        ),
        migrations.RenameIndex(
            model_name='productdownloadevent',
            new_name='products_pr_product_16fce6_idx',
            old_name='products_pr_product__6d3e74_idx',
        ),
    ]
