# Generated by ChatGPT on 2026-02-10
from __future__ import annotations

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_stripewebhookdelivery_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerFulfillmentTask",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("is_completed", models.BooleanField(default=False, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fulfillment_tasks", to="orders.order", db_index=True)),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fulfillment_tasks", to=settings.AUTH_USER_MODEL, db_index=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="sellerfulfillmenttask",
            constraint=models.UniqueConstraint(fields=("seller", "order"), name="uniq_fulfillment_task_per_seller_order"),
        ),
        migrations.AddIndex(
            model_name="sellerfulfillmenttask",
            index=models.Index(fields=["seller", "is_completed", "created_at"], name="orders_sft_seller_done_idx"),
        ),
    ]
