# Generated by Django 5.1.15 on 2026-02-02 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_seller__f467b3_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='marketplace_sales_percent_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform % cut captured at order creation time. Changing SiteConfig later does not change this order.', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee_cents_snapshot',
            field=models.PositiveIntegerField(default=0, help_text='Optional flat fee captured at order creation time (in cents).'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='marketplace_fee_cents',
            field=models.PositiveIntegerField(default=0, help_text='Platform fee on this line (percent-based; flat fee allocation may be added later).'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_net_cents',
            field=models.PositiveIntegerField(default=0, help_text='What seller should receive for this line (gross - marketplace_fee).'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('stripe_session_created', 'Stripe session created'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('transfer_created', 'Transfer created'), ('warning', 'Warning')], max_length=64),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(help_text='Seller snapshot at time of purchase.', on_delete=django.db.models.deletion.PROTECT, related_name='sold_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['stripe_event_id'], name='orders_stri_stripe__3096e2_idx'),
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['event_type', '-created_at'], name='orders_stri_event_t_146523_idx'),
        ),
    ]
