# Generated by Django 5.1.15 on 2026-02-03 16:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_stripewebhookevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='marketplace_sales_percent_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Marketplace % cut captured at order creation time.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform_fee_cents_snapshot',
            field=models.PositiveIntegerField(default=0, help_text='Legacy flat fee snapshot (NOT USED). Keep at 0.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='marketplace_fee_cents',
            field=models.PositiveIntegerField(default=0, help_text='Marketplace fee on this line (percent-based).'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='seller_net_cents',
            field=models.PositiveIntegerField(default=0, help_text='Seller net on this line (gross - marketplace_fee).'),
        ),
    ]
