# Generated by Django 5.1.15 on 2026-02-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productphysical_num_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdigital',
            name='compatible_software',
            field=models.CharField(blank=True, help_text='e.g., Windows, macOS, Linux', max_length=255),
        ),
        migrations.AddField(
            model_name='productdigital',
            name='license_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal Use Only'), ('commercial', 'Commercial Use Allowed'), ('educational', 'Educational Use'), ('open_source', 'Open Source / CC License')], help_text='Usage rights for this file', max_length=20),
        ),
        migrations.AddField(
            model_name='productdigital',
            name='requirements',
            field=models.TextField(blank=True, help_text='System requirements, dependencies, installation notes, etc.'),
        ),
        migrations.AddField(
            model_name='productdigital',
            name='software_requirements',
            field=models.CharField(blank=True, help_text='e.g., Fusion 360, FreeCAD, Blender', max_length=255),
        ),
    ]
