# Generated by Django 5.1.15 on 2026-02-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productdigital_compatible_software_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_purchases_per_buyer',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times a single buyer can purchase this product. Leave blank for no limit.', null=True),
        ),
    ]
