# Generated by Django 5.1.15 on 2026-02-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_8a7c6b_idx',
            old_name='notificatio_user_id_4c3b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_8b0d79_idx',
            old_name='notificatio_user_id_2c0c9d_idx',
        ),
    ]
