# Generated by Django 5.1.15 on 2026-02-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_event_t_6c35be_idx',
            old_name='analytics_a_event_t_6eac2b_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_path_27a354_idx',
            old_name='analytics_a_path_3c4bf9_idx',
        ),
    ]
