# Generated by Django 5.1.15 on 2026-02-08 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_carrier'),
        ('products', '0015_remove_productphysical_depth_mm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_tip',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this line is a buyer tip (100% to seller; no marketplace fee).'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['is_tip', 'created_at'], name='orders_orde_is_tip_573fe9_idx'),
        ),
    ]
