# Generated by Django 5.1.15 on 2026-02-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_stripewebhookdelivery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stripewebhookdelivery',
            new_name='orders_stri_status_41a038_idx',
            old_name='orders_stri_status_1d2b32_idx',
        ),
        migrations.RenameIndex(
            model_name='stripewebhookdelivery',
            new_name='orders_stri_event_t_1bc4b6_idx',
            old_name='orders_stri_event_t_b0b5fa_idx',
        ),
    ]
