# Generated by Django 5.1.15 on 2026-02-01 21:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('order_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='draft', max_length=24)),
                ('kind', models.CharField(choices=[('digital', 'Digital only'), ('physical', 'Physical only'), ('mixed', 'Mixed (digital + physical)')], default='physical', max_length=16)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('tax_cents', models.PositiveIntegerField(default=0)),
                ('shipping_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shipping_name', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_phone', models.CharField(blank=True, default='', max_length=64)),
                ('shipping_line1', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_line2', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_city', models.CharField(blank=True, default='', max_length=120)),
                ('shipping_state', models.CharField(blank=True, default='', max_length=120)),
                ('shipping_postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('shipping_country', models.CharField(blank=True, default='', max_length=2)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, help_text='Registered buyer. Null means guest checkout.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('created', 'Created'), ('stripe_session_created', 'Stripe session created'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('warning', 'Warning')], max_length=64)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_cents', models.PositiveIntegerField(default=0)),
                ('is_digital', models.BooleanField(default=False)),
                ('requires_shipping', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_order_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='orders_orde_buyer_i_67c51b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['kind', '-created_at'], name='orders_orde_kind_264a78_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-paid_at'], name='orders_orde_paid_at_33bb25_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', '-created_at'], name='orders_orde_order_i_974e12_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_4ba133_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'created_at'], name='orders_orde_product_9a366c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller', 'created_at'], name='orders_orde_seller__d8f1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller', 'order'], name='orders_orde_seller__f467b3_idx'),
        ),
    ]
