# Generated by Django 5.1.15 on 2026-02-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_sellerfulfillmenttask'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sellerfulfillmenttask',
            new_name='orders_sell_seller__00928a_idx',
            old_name='orders_sft_seller_done_idx',
        ),
    ]
