# Generated by Django 5.1.15 on 2026-02-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_analytics_a_event_t_6eac2b_idx_analytics_a_event_t_6c35be_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('PAGEVIEW', 'Pageview'), ('THROTTLE', 'Throttle')], default='PAGEVIEW', max_length=32),
        ),
    ]
