# Generated by Django 5.1.15 on 2026-02-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsevent_hardening'),
        ('analytics', '0003_alter_analyticsevent_event_type'),
    ]

    operations = [
    ]
