# Generated by Django 5.1.15 on 2026-02-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewreply'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reviewreply',
            new_name='reviews_rev_seller__cdc456_idx',
            old_name='reviews_repl_seller__b0a2c2_idx',
        ),
    ]
