# Generated by ChatGPT on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_orderitem_buyer_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="carrier",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
