# Generated by Django 5.1.15 on 2026-02-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_orders_stri_status_1d2b32_idx_orders_stri_status_41a038_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeWebhookDelivery',
        ),
    ]
