# Generated by ChatGPT on 2026-02-09
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_delete_stripewebhookdelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookDelivery",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=255, blank=True, default="")),
                ("status", models.CharField(max_length=16, choices=[("received","Received"),("processed","Processed"),("duplicate","Duplicate (already processed)"),("error","Error")], default="received")),
                ("request_id", models.CharField(max_length=64, blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("processed_at", models.DateTimeField(null=True, blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "-received_at"], name="orders_stri_status_3e8c3a_idx"),
                    models.Index(fields=["event_type", "-received_at"], name="orders_stri_event_t_2f0d2f_idx"),
                ],
            },
        ),
    ]
