# Generated by Django 5.1.15 on 2026-02-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_stripewebhookdelivery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stripewebhookdelivery',
            new_name='orders_stri_status_41a038_idx',
            old_name='orders_stri_status_3e8c3a_idx',
        ),
        migrations.RenameIndex(
            model_name='stripewebhookdelivery',
            new_name='orders_stri_event_t_1bc4b6_idx',
            old_name='orders_stri_event_t_2f0d2f_idx',
        ),
    ]
