# Generated by Django 5.1.15 on 2026-02-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={},
        ),
        migrations.RenameIndex(
            model_name='favorite',
            new_name='favorites_f_user_id_27e810_idx',
            old_name='favorites_f_user_id_0cdd6a_idx',
        ),
        migrations.RenameIndex(
            model_name='favorite',
            new_name='favorites_f_product_fb8b70_idx',
            old_name='favorites_f_product_79d541_idx',
        ),
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='favorites_w_user_id_b03418_idx',
            old_name='favorites_w_user_id_4e0f34_idx',
        ),
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='favorites_w_product_0bc06f_idx',
            old_name='favorites_w_product_d714d9_idx',
        ),
    ]
