# Generated by Django 5.1.15 on 2026-02-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_rootcategory_rootcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RootCategory',
        ),
        migrations.CreateModel(
            name='RootCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
    ]
