# Generated by Django 5.1.15 on 2026-02-02 19:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_stripewebhookevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reason', models.CharField(choices=[('damaged', 'Item arrived damaged'), ('not_as_described', 'Not as described'), ('late', 'Arrived too late'), ('wrong_item', 'Wrong item received'), ('other', 'Other')], max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='requested', max_length=16)),
                ('line_subtotal_cents_snapshot', models.PositiveIntegerField(default=0)),
                ('tax_cents_allocated_snapshot', models.PositiveIntegerField(default=0)),
                ('shipping_cents_allocated_snapshot', models.PositiveIntegerField(default=0)),
                ('total_refund_cents_snapshot', models.PositiveIntegerField(default=0)),
                ('stripe_refund_id', models.CharField(blank=True, default='', max_length=255)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('seller_decided_at', models.DateTimeField(blank=True, null=True)),
                ('seller_decision_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests_made', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='orders.order')),
                ('order_item', models.OneToOneField(help_text='At most one refund request per order line item.', on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='orders.orderitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='refunds_ref_status_9c10bf_idx'), models.Index(fields=['seller', 'status', '-created_at'], name='refunds_ref_seller__164a21_idx'), models.Index(fields=['buyer', 'status', '-created_at'], name='refunds_ref_buyer_i_3df5dc_idx'), models.Index(fields=['order', '-created_at'], name='refunds_ref_order_i_1f455e_idx')],
            },
        ),
    ]
