# Generated by Django 5.1.15 on 2026-02-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_refundattempt'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='refundattempt',
            name='refunds_ref_refund__a1d0a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='refundattempt',
            name='refunds_ref_success_7f2c1a_idx',
        ),
    ]
