# Generated by Django 5.1.15 on 2026-02-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_is_manual',
            field=models.BooleanField(default=False, help_text='If checked, slug will not auto-update when the title changes.'),
        ),
    ]
